apiVersion: config.luxaslabs.com/v1beta1
kind: MyAppConfiguration
clientConnection:
  burst: 200
  kubeconfig: /var/my-app/kubeconfig.yaml
  qps: 100
serverAddress: 1.2.3.4
httpsPort: 8080
tlsConfig:
  tlsCertFile: /var/my-app/cert.crt
  tlsPrivateKeyFile: /var/my-app/cert.key
